let superHeroName = 'Batman';
let name = 'Bruce Wayne';
let fly = false;
let hasBatmobile = true;
let life = undefined;
let freeTime = null;
console.log('superHeroName', superHeroName, typeof superHeroName);
console.log('name',name, typeof name);
console.log('fly', fly, typeof fly);
console.log('hasBatmobile', hasBatmobile, typeof hasBatmobile);
console.log('life', life, typeof life);
console.log('freetime', freeTime, typeof freeTime);
